// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at b6a6625a505e2054558f629e08f8d61c3386929d
//
#![recursion_limit = "2048"]
#![no_std]
pub mod axicdma;
pub mod defines;
pub mod doe_mbox;
pub mod el2_pic_ctrl;
pub mod fuses;
pub mod i3c;
pub mod lc_ctrl;
pub mod mbox;
pub mod mci;
pub mod otp_ctrl;
pub mod primary_flash_ctrl;
pub mod secondary_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
