// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c543994e408107569ceb26e66260534826b0c8bc
//
//
// Warning: caliptra-ss was dirty: M third_party/i3c-core
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
