// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c543994e408107569ceb26e66260534826b0c8bc
//
//
// Warning: caliptra-ss was dirty: M third_party/i3c-core
//

use std::sync::atomic::{AtomicBool, Ordering};

static WARN_ON_STUB: AtomicBool = AtomicBool::new(true);

/// Enable or disable warning logs when auto-generated register stubs
/// handle a read/write that was not overridden by the peripheral implementation.
pub fn set_stub_warnings(enabled: bool) {
    WARN_ON_STUB.store(enabled, Ordering::Relaxed);
}

/// Returns `true` if stub warning logs are enabled.
#[inline]
pub fn stub_warnings_enabled() -> bool {
    WARN_ON_STUB.load(Ordering::Relaxed)
}
